<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>br.com.victorsfec.fanorona</groupId><artifactId>sockets</artifactId><version>1.0</version>
  <name>Fanorona com Sockets</name>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>25</maven.compiler.release>
  </properties>
  <build><plugins>
    <plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><version>3.13.0</version></plugin>
    <plugin><groupId>org.codehaus.mojo</groupId><artifactId>exec-maven-plugin</artifactId><version>3.3.0</version>
      <executions><execution><id>testes-regras-e-tcp</id><phase>test</phase><goals><goal>java</goal></goals>
      <configuration><mainClass>br.com.victorsfec.fanorona.AppTest</mainClass><classpathScope>test</classpathScope></configuration></execution></executions>
    </plugin>
    <plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-jar-plugin</artifactId><version>3.4.2</version><executions>
      <execution><id>server</id><phase>package</phase><goals><goal>jar</goal></goals><configuration><classifier>server</classifier><archive><manifest><mainClass>br.com.victorsfec.fanorona.server.FanoronaServer</mainClass></manifest></archive></configuration></execution>
      <execution><id>client</id><phase>package</phase><goals><goal>jar</goal></goals><configuration><classifier>client</classifier><archive><manifest><mainClass>br.com.victorsfec.fanorona.client.FanoronaClient</mainClass></manifest></archive></configuration></execution>
    </executions></plugin>
  </plugins></build>
</project>
